### ISSUE TITLE
From PeerJ feedback: add more info about planning for cost of long term storage

### ISSUE THREAD

**Issue by fmichonneau** [emhart/10-simple-rules-data-storage#106]

**Comment by dlebauer** [comment]
- summary of contemporary costs for platforms mentioned in paper
- how much can be stored for free, and where?
- funding for long term storage; institutional solutions
- reliability?

References:
- [Deelman et al 2008 The cost of doing science in the cloud](https://github.com/emhart/10-simple-rules-data-storage/files/27213/deelman_sc08_corrected.pdf)
- [Beerman and Cerf 2013 Who will pay for public access to research data?](https://github.com/emhart/10-simple-rules-data-storage/files/27221/berman2013wwp.pdf)
- Institutional solutions, e.g. [U of I Box](http://techservices.illinois.edu/services/u-i-box/details)
