### ISSUE TITLE
References for advanced treatments

### ISSUE THREAD

**Issue by khinsen** [emhart/10-simple-rules-data-storage#110]
Something I wish this paper would contain is references to articles and books that treat more advanced issues in data management. Something like a "further reading" section. I do realize that this could potentially become huge, which would be counter-productive. I'd say one or two references per topic would be fine, with topic candidates being "data archiving", "data models and formats", and "databases".

**Comment by dlebauer** [comment]
think a few of these have come up. Here are a few, but these don't really cover CS textbook-level info on data:
- [DataONE_Best_Practices_Primer_020212.pdf](https://github.com/emhart/10-simple-rules-data-storage/files/22548/DataONE_Best_Practices_Primer_020212.pdf)
- [White et al 2013 Nine simple ways to make it easier to re-use your data](https://github.com/emhart/10-simple-rules-data-storage/files/22550/4608-9821-1-PB.pdf)
- [DataOne Education Modules](https://www.dataone.org/education-modules)
- [Data Carpentry](http://datacarpentry.org/) 
- ["The challenge of combining 176 x #otherpeoplesdata" by Daniel Falster and others](https://ropensci.org/blog/2015/06/03/baad/) provides a summary of rules (lessons learned) with examples from the creation of the [Biomass And Allometry Database (BAAD)](https://github.com/dfalster/baad)
- [The "Data Curation Toolkit" by Purdue](http://datacurationprofiles.org/purpose) (this may be too in depth)
- [Wickham Tidy Data](https://github.com/emhart/10-simple-rules-data-storage/files/22555/tidy-data.pdf)

**Comment by PBarmby** [comment]
Commit above doesn't include all of the references listed since some were already there. The Falster et al post, while very interesting, fell (IMO) a little outside of the current paper's subject, so I left it out.
