### ISSUE TITLE
From Wes Turner e-mail

### ISSUE THREAD

**Issue by emhart** [emhart/10-simple-rules-data-storage#113]
via  Wes Turner - wes.turner@gmail.com

 LinkedData
- Rule 5, line 95:
  Rule 7, line 150:
  - RDF, CSVW, JSONLD
- Discoverability and URI Linked metadata (about things with types from vocabularies of things with URIs and rdfs:label@en)
- "Linked Reproducibility"
  #linked-reproducibility
  - https://wrdrd.com/docs/consulting/data-science#tensimplerules-for-reproducible-computation-research
  - https://wrdrd.com/docs/consulting/knowledge-engineering.html#qb #rdf #csvw #jsonld

please feel free to reuse any of these reference links / "information assets".

without need for standard form, sphinx and ReStructuredText preserve hyperlinks.

**Comment by westurner** [comment]
- RDFa

**Comment by westurner** [comment]
- https://schema.org/EmailMessage
- Thing > CreativeWork > https://schema.org/Dataset > https://schema.org/Datafeed (.dataFeedElement)
