### ISSUE TITLE
Thank pre-submission commenters

### ISSUE THREAD

**Issue by PBarmby** [emhart/10-simple-rules-data-storage#116]
Maybe this is not standard in every field but it would be in mine.
Commenters include K Hinsen (GH), Graham Pugh (PeerJ)

**Comment by karawoo** [comment]
Do you mean in the acknowledgments? I'm in favor of this.

**Comment by naupaka** [comment]
I am also definitely in favor of adding them to the acknowledgments.

**Comment by jhollist** [comment]
:+1:

On Sat, Nov 14, 2015 at 1:50 PM, Naupaka Zimmerman <notifications@github.com

> wrote:
> 
> I am also definitely in favor of adding them to the acknowledgments.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/emhart/10-simple-rules-data-storage/issues/116#issuecomment-156732782
> .

## 

Jeff W. Hollister
email: jeff.w.hollister@gmail.com
google voice: 401 326 2531
cell: 401 556 4087

**Comment by tpoisot** [comment]
Me three.

Kara Woo (11/14):

**Comment by fmichonneau** [comment]
@PBarmby, could you please open a  PR so we can merge the changes you committed to your fork? Thanks!

**Comment by PBarmby** [comment]
Already done, see #117.
