### ISSUE TITLE
store data in common open format

### ISSUE THREAD

**Issue by dlebauer** [emhart/10-simple-rules-data-storage#12]
An important one from [DataOne](https://www.dataone.org/best-practices/document-and-store-data-using-stable-file-formats). 
I found this in a [list of storage-tagged rules from DataOne](https://www.dataone.org/best-practices/storage) thinking "there must be a list of rules there". Indeed, there is, but they are all too technical for a list of "Simple Rules". Thus, the list from above could simplified to 

Features of a good format:
- open source format (e.g. NetCDF instead of ArcGIS 
- ASCII if appropriate (text files)
- software agnostic
- formats used by wider community where possible
- meaningful alternatives to 'NULL'

**Comment by jhollist** [comment]
+1 for this, although I'd simplify rule to, "store data in common open format"

(done, changed from "Store data in ASCI, preferably csv, or other common open formats") - DSL

**Comment by tpoisot** [comment]
I support that strongly.

**Comment by karawoo** [comment]
:+1:

**Comment by emhart** [comment]
:+1: I'm not sure that we should suggest how to code NULL values though, as that doesn't seem like it explicitly relates to storage of data.

**Comment by karawoo** [comment]
I agree, @emhart, I think that point and similar ones are well covered in [Nine simple ways to make it easier to (re)use your data](http://library.queensu.ca/ojs/index.php/IEE/article/view/4608/4898).

**Comment by snim2** [comment]
This also relates to #20 and possibly #11.

I live and work quite close an area which is governed (sort of!) by the largest City Council in Europe. There has been a push in the last few years to get this Council to open up its data. Both data about its budget and democratic process, and also data that is more relevant here - for example data about pollution and the environment, or waste management. Some people in the Council are more on board with this than others, but few really understand what is needed for this sort of open data to be useful. The result is that many well meaning people "open" their data by converting a perfectly reasonable spreadsheet to a PDF and putting that PDF on a website. 

To be fair, PDFs can be scraped, but not without difficulty, and it would save time and effort just to use the original spreadsheet
