### ISSUE TITLE
Submit to PLoS Comp Bio

### ISSUE THREAD

**Issue by naupaka** [emhart/10-simple-rules-data-storage#120]
Just a ping to see if we are ready to submit this officially. Are there changes that still need to be made/incorporated from the preprint feedback?

**Comment by gvwilson** [comment]
:+1: from me.

**Comment by emhart** [comment]
I think there are a few, then we can make the submission.  I'll take a crack tonight.

**Comment by emhart** [comment]
@naupaka Submitted.  My intuition is that it will get kicked back at us because the editorial section say "invitation only", but we'll see. :metal:

**Comment by fmichonneau** [comment]
Thanks for submitting @emhart ! I just checked the website and it says "under review", so we might be good :smile: We may want to submit this updated version to PeerJ Pre-prints as well.

**Comment by emhart** [comment]
@fmichonneau Updated version sent to peerj, I also tagged the version for the initial submission as well as did a "release".

**Comment by fmichonneau** [comment]
Awesome! Thanks

**Comment by emhart** [comment]
In case folks are curious the manuscript is now under review.

**Comment by fmichonneau** [comment]
while working on a different manuscript, I noticed that the latest preprint on PeerJ is tagged "awaiting revision" and hasn't been released yet. @emhart, do you know what is holding it up?

**Comment by emhart** [comment]
Thanks for the notice, the feedback got put into spam by gmail.  I had to
remove the PLoS logo.  I've edited the latex template and pushed it up to a
new branch if there are anymore preprint submissions.

**Comment by fmichonneau** [comment]
Great, thanks!

**Comment by emhart** [comment]
Manuscript accepted with minor revisions so closing.
