### ISSUE TITLE
the wisdom of Wu or Cash Rules Everything Around Me (C.R.E.A.M.)  or how will we pay for this?

### ISSUE THREAD

**Issue by emhart** [emhart/10-simple-rules-data-storage#130]
Hi all, so now that we've been accepted we'll need to figure out how to handle the publishing fee.  I think we have 3 options as I recall.
1. Ask for a waiver
2. Ask the SWC powers that be for the money
3. @jhollist at one point suggested he might be able to get the EPA to pay.  Not sure where we still stand on this.

![giphy 11](https://cloud.githubusercontent.com/assets/1039395/14894162/3718ce66-0d27-11e6-947e-83ded53a2f28.gif)

**Comment by jhollist** [comment]
I am willing to make the ask, but we would have to subject the manuscript to internal EPA review.  That wouldn't be too bad and quite frankly could happen in parallel to review for the journal.  Even then I am not guaranteed to get a yes on this one.  

I think 1 or 2 (or a combination) would be the best tact.  We can save the EPA route as a last option.

**Comment by dlebauer** [comment]
Fourth is ask anyone w/ a budget for publication fees to pony up.

How much?

**Comment by jhollist** [comment]
It is a bit pricey. $2250

More at http://journals.plos.org/ploscompbiol/s/publication-fees

**Comment by emhart** [comment]
The fee is  $2,250. I'm happy to go to Greg and Jonah if no one has any publication budget.  So I think the current order of preference is:
1. Anyone with budget steps forward to cover it
2. We ask Jonah / Greg
3. We ask for a waiver
4. Consider the EPA

**Comment by jhollist** [comment]
I concur!

**Comment by emhart** [comment]
So...ahem...anyone have $2250?  Or should I go right to Greg?

**Comment by tpoisot** [comment]
I have 99 problems but being able to spend 2250 ain't one.
I can pay part of it and would be happy to, though.
Unless we have a secret editorial board discount I don't know of...

**Comment by dlebauer** [comment]
I can also pay part.

**Comment by karawoo** [comment]
I don't have any funds to contribute, unfortunately.

**Comment by dlebauer** [comment]
I need a few days to check

**Comment by gvwilson** [comment]
Software Carpentry can kick in $500 toward this. cc @jduckles

**Comment by emhart** [comment]
Great!  Thanks @gvwilson, looks like we should have no worries coming up with the fees.  Thanks everyone.

**Comment by jduckles** [comment]
Just let me know at jduckles@software-carpentry.org when you need me to disburse the partial payment.

**Comment by emhart** [comment]
Finally got the provisional acceptance.  a few typos and then all that's left is to pay the bills.  @dlebauer @tpoisot and @jduckles I'll be in touch over e-mail to figure out how best to pay the bills.  It's been a long time coming, but it should be out soon.

**Comment by naupaka** [comment]
w00t! 🎉

**Comment by emhart** [comment]
This has been sorted out, and paper is production, closing.
