### ISSUE TITLE
Final pass for typos etc. before submission

### ISSUE THREAD

**Issue by snim2** [emhart/10-simple-rules-data-storage#134]
Since several of the reviewer comments were about typos etc. it would probably be a good idea to look over the final submission before it goes out. I'm happy to do this myself, but I think having one other person on board would also help (two heads better than one, etc.).

**Comment by jhollist** [comment]
I'd be happy to take a pass at it.  Probably easiest if one of us goes
first?  I won't have time today, but can make some time tomorrow.

On Sun, May 1, 2016 at 5:08 AM, Sarah Mount notifications@github.com
wrote:

> Since several of the reviewer comments were about typos etc. it would
> probably be a good idea to look over the final submission before it goes
> out. I'm happy to do this myself, but I think having one other person on
> board would also help (two heads better than one, etc.).
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/emhart/10-simple-rules-data-storage/issues/134

## 

Jeff W. Hollister
email: jeff.w.hollister@gmail.com
google voice: 401 326 2531
cell: 401 556 4087

**Comment by snim2** [comment]
Thanks! I think there are probably a few PRs to merge first...

**Comment by karawoo** [comment]
If we need a third set of eyes I'm happy to do this as well, but I agree we should address all the other reviewer comments first.

**Comment by jhollist** [comment]
Agreed on waiting till all other PRs are in.  I was just so excited to
proof read, that I neglected to think about that!

And a third set of eyes certainly wouldn't hurt!

On Sun, May 1, 2016 at 12:53 PM, Kara Woo notifications@github.com wrote:

> If we need a third set of eyes I'm happy to do this as well, but I agree
> we should address all the other reviewer comments first.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/emhart/10-simple-rules-data-storage/issues/134#issuecomment-216055079

## 

Jeff W. Hollister
email: jeff.w.hollister@gmail.com
google voice: 401 326 2531
cell: 401 556 4087

**Comment by emhart** [comment]
I think all the PR's are in (it's been 11 days)  I will make one more pass and then leave it up for a few days, then write the letter for the resubmission.  So last call for any changes.

**Comment by karawoo** [comment]
I don't think we addressed Reviewer 3's comments (#128) yet?

**Comment by emhart** [comment]
@karawoo Nope, no one had tackled that yet so I was going to when I make another pass.

**Comment by naupaka** [comment]
I am also happy to look over and proofread, but I won't be able to work on it for the next 2 weeks. After that, I'm happy to help do whatever needs done, read over a final draft, or etc.

**Comment by naupaka** [comment]
I will do a pass to address remaining reviewer concerns and typos, etc by the end of the week, unless anyone else is currently working on changes already.

**Comment by naupaka** [comment]
I will do a last pass to check over things added in #138 while I'm on the plane tomorrow. 

Quick Q (@emhart @PBarmby @karawoo): what's the protocol for generating the pdf from the md for the response to reviewers? pandoc locally? Didn't notice a makefile. No worries if there's no preference, just didn't want to goof something up.

**Comment by emhart** [comment]
@naupaka it's pretty basic so I've just been using 

`pandoc reviewer_response.md -o reviewer_response.pdf`  

Didn't seem to warrant a makefile.

**Comment by naupaka** [comment]
Sounds like a plan.

**Comment by emhart** [comment]
@naupaka Are you still able to make a last pass?  Otherwise I can do it this week and then I'll submit.

**Comment by naupaka** [comment]
@emhart yes definitely sorry for the delay. I have all my comments on a hard copy and just need to edit them in. Would it be ok to get that done by the end of the week? (I'm teaching at a workshop at NEON all week and it's a bit front loaded)

**Comment by emhart** [comment]
No worries 😄   Just wanted to check in.  Yikes, teaching at NEON?? I've heard crazy things about that place 😆

**Comment by naupaka** [comment]
Working on this now; should have the PR submitted today.

**Comment by emhart** [comment]
Awesome, thanks @naupaka

**Comment by naupaka** [comment]
Finally: just submitted PR #140. Sorry for the delay.
