### ISSUE TITLE
Revised Submission

### ISSUE THREAD

**Issue by emhart** [emhart/10-simple-rules-data-storage#142]
All the revisions have been submitted and [I've created a release](https://github.com/emhart/10-simple-rules-data-storage/releases/tag/1.1).  Thanks all for your work on the revisions.

**Comment by snim2** [comment]
Many thanks @emhart

**Comment by jhollist** [comment]
Agreed!  thanks @emhart for herding this fine group of cats!

**Comment by naupaka** [comment]
So has this been resubmitted then?

**Comment by emhart** [comment]
Yes

**Comment by snim2** [comment]
@emhart mind if I delete the merged branches? We have quite a few now!

**Comment by emhart** [comment]
Sure.

**Comment by snim2** [comment]
OK done! There are two branches with un-merged commits: `rule-9.2` and `preprintv2`. I'm not sure what their status is.
