### ISSUE TITLE
Check proofs

### ISSUE THREAD

**Issue by emhart** [emhart/10-simple-rules-data-storage#143]
Hi All, I received this e-mail this afternoon.  They've asked for a 2 day turn around, which I know is quick, but I'd like to stick to it.  I will make the requested changes.  I think we should submit one unified document so I think this final stage is best managed by you simply replying to this issue with the change you want.  Then I will go through and make all the requested changes by you all and PLOS, annotating them as they ask.  Thanks again all.
## Full text

[pcbi.1005097_CEtoAU.pdf](https://github.com/emhart/10-simple-rules-data-storage/files/499103/pcbi.1005097_CEtoAU.pdf)

Dear Dr. Hart,

Your copyedited manuscript is now ready for review. In order to preserve the LaTeX formatting, it was typeset prior to copyediting, and thus copyediting changes have been marked in the PDF proof, attached to this email. Please take note of the comments addressed to "AU" and answer these queries throughout, and also add any additional changes using the Adobe markup and comment tools as needed. Please return the file to me via attachment to email when you have completed your review. This will be your last chance to make any changes before publication, so please review carefully.

We will need your response within 2 working days if possible.

See the end of this email for the following:
- Instructions for reviewing the proof
- Recommended checks on the proof

Please let me know if you have any questions or concerns.

All best,

Jennifer Fricker
PLOS Production

---

Instructions for Mark-up and Return of your Manuscript:

Important: Adobe Acrobat (Pro or Reader) is required for PDF proof markup. Adobe Acrobat Reader is available as a free download: http://get.adobe.com/reader/.
- Only Adobe Acrobat Commenting Tools are accepted.
- Use these three mark-up types whenever possible (Annotations tools in Comment menu):
  - Insert new content
  - Replace existing content
  - Delete existing content (strikethrough)
  - Sticky Note (for corrections concerning Figures only and to reply to AU queries)
- To request replacement of figures or tables (only in cases of misleading scientific inaccuracies or printer's errors), use the Sticky Note tool to explain what corrections you have made to these objects. When you return your marked-up PDF to me via email, also attach replacement figures or tables as separate files. Note: please ensure that figure specifications remain the same as those in your accepted files.

Recommended Checks

**_This is the last time you will see your article before publication, so please review the proof carefully.**_

Please ensure that you review:
- Title and running title
- Author names and affiliations
- Data in text
- Data in tables
- Figures and figure legends

**Comment by naupaka** [comment]
I just went through the whole text, and don't have any other changes to make. The comments all seem helpful and quick to accept/reply to. Congrats to all; it's actually going to be a done thing!

**Comment by jhollist** [comment]
I also took a quick look.  Nothing too onerous there.

WRT to the comment in the acknowledgements about me!  If we can I'd prefer to change author for me to Jeffrey W. Hollister.  Also we can switch JWH to J. Hollister to match the other names in the acknowledgments.

And this is fantastic that we all got this thing done!  

So what is our next paper going to be?  :smile:

**Comment by karawoo** [comment]
Looks good to me! For the broken Toy Story 2 link, I think it originally went to [this video](https://www.youtube.com/watch?v=8dhp_20j0Ys), but there are also news stories like [this one](http://thenextweb.com/media/2012/05/21/how-pixars-toy-story-2-was-deleted-twice-once-by-technology-and-again-for-its-own-good/) that might be better to use.

**Comment by PBarmby** [comment]
Gah, sorry I missed this. Ted, I assume everything is good and there's nothing more for anyone to do?

**Comment by emhart** [comment]
@PBarmby All good, the paper is in production with the few edits Jeff and Kara suggested.  Closing because window for edits is closed.
