### ISSUE TITLE
Data should be stored differently at different steps of the process

### ISSUE THREAD

**Issue by tpoisot** [emhart/10-simple-rules-data-storage#16]
Basically, the format for long-term archival is not the same format that is needed for day-to-day analysis. I'd say that in the opposite direction, actually: don't archive your data in the format that makes sense for you in your day-to-day use.

**Comment by jhollist** [comment]
:+1:  I was going to to add something similar, but you beat me to it @tpoisot !

This general idea is captured in the discussion in https://github.com/swcarpentry/site/issues/797.  Another tangent to this is the idea that not all data are created equal wrt accessibility (i.e. Personally Identifiable Information, Conf. Business Info, etc.)  I don't personally work with this type of data so someone else should probably chime in.  Perhaps that should be another rule?

**Comment by PBarmby** [comment]
See also  the second ref in #3 for some comments re: different formats for different usage.

**Comment by emhart** [comment]
@tpoisot Could you share a use case here? Are you thinking that it might be archived as plain text but you'd want to access it in a SQL database?
