### ISSUE TITLE
Storage location should consider expected analysis 

### ISSUE THREAD

**Issue by PBarmby** [emhart/10-simple-rules-data-storage#19]
In many cases fast access between disk and compute server is needed, so that I/O doesn't bog down the entire process.

**Comment by emhart** [comment]
I think this is somewhat related to size considerations in #25.  Are you thinking about this in terms of sharing data with other people, or sharing it in your lab?  If it's the latter, are you thinking about database choice?

**Comment by PBarmby** [comment]
Agreed it's related to size considerations. I wasn't really thinking about this in terms of sharing, more in terms of "I have this big dataset and now I need to do some big computation with it" in which case you often want the disk with the data to be close to the machine doing the computation.

**Comment by tpoisot** [comment]
This is also part of what I had in mind with #16 -- raw data go somewhere in the cloud or on a server, and data ready for consumption are in your SSD
