### ISSUE TITLE
Collaborator status

### ISSUE THREAD

**Issue by emhart** [emhart/10-simple-rules-data-storage#21]
I believe I've given collaborator access to everyone, so you all should be able to push to the repo now if you want to make changes to the README, or when we're writing.

**Comment by tpoisot** [comment]
I'd encourage people to push to their own branches rather than on master, though.

**Comment by dlebauer** [comment]
@tpoisot do you mean "push to their own forks at `username/repo`" or "create a new branch in the emhart repository"

presumably followed by a pull request? (in practice, these important part seems to be using pull requests rather than pushing to master). Exceptions for trivial changes?

**Comment by emhart** [comment]
With collaborator access you can also merge PR's so you can merge your own branches and PR's.  I agree once we actually get to writing, we should decide on a workflow (branches or otherwise).

**Comment by snim2** [comment]
I think most GitHub workflows encourage peer review, in the sense that if one person proposes a PR then they would not normally merge their own PR but have it reviewed by others first. This seems like a good practice to me.

**Comment by dlebauer** [comment]
Yep @snim2 +1 that's what I meant by 'the important part is pull request', implying but not clearly stating '...for others to review'
