### ISSUE TITLE
Basic Timeline

### ISSUE THREAD

**Issue by emhart** [emhart/10-simple-rules-data-storage#24]
Hi All,

I wanted to propose a timeline for generating ideas.
- _March 16_ - All proposed rules submitted and discussed
- _March 23_ - Final 10 rules decided, authors assigned to topics
- _April 13_ - Rough draft of rules submitted to repo

I'm just sort of putting this out there for us all, but personally I find it useful to have a time line (to break) to help me prioritize all the other things I'm working on.  Please amend this if you think it's unreasonable I just put this together as a starting point.

**Comment by snim2** [comment]
+1

**Comment by tpoisot** [comment]
Agreed. I created milestones with dates. We use them in the lab not to miss deadlines, it's pretty efficient.

**Comment by dlebauer** [comment]
@emhart Can you define "submitted and discussed"? Have we completed this? Now we have three days for the final rules?

**Comment by emhart** [comment]
@dlebauer I was hoping that we would have completed our discussion of the rules and begun to finalize them.  I'm going to send out on more request for rules and then try and synthesize them.

**Comment by tpoisot** [comment]
:+1:
