### ISSUE TITLE
Consider the size of your data

### ISSUE THREAD

**Issue by emhart** [emhart/10-simple-rules-data-storage#25]
Data size matters.  As @stephenturner points out there's a vast difference between data created by NEON and a data set you might archive on Figshare from your PhD (if you're an ecologist anyway).  How you store your data has to take these size considerations.  It will determine where you archive your data, how it's backed-up and how it's shared.

**Comment by dlebauer** [comment]
lemma 1: storage costs and transfer / compute time are trivial if data is small, but can add up if data is large. At some size, it is not practical to store data - there are trade offs among cost, information content, and accessibility.
