### ISSUE TITLE
Consider privacy concerns.

### ISSUE THREAD

**Issue by emhart** [emhart/10-simple-rules-data-storage#26]
How can you store data that has private information?  Is it with anonymized via a hash that can't be worked backwards? Do you maintain that hash and encrypt it?  I'm not really equipped to answer this question since I don't deal with human subject data, but maybe someone else could chime in.

**Comment by dlebauer** [comment]
Is it necessary to distinguish data you don't want others to see from data you don't want others to use?

**Comment by emhart** [comment]
I was just thinking about that.  If we're thinking about storage best practices locally, then encryption may be important.  Obviously if the data is meant to be shared then there are other things to worry about.  It seems there's three scenarios with privacy concerns.
1. You want to share data with collaborators that is private, what are encryption best practices?
2. You want to share data publicly that has personal information, so how do you anonymize it?
3. You want to store the data locally, and protect personal information.

**Comment by snim2** [comment]
As it happens I'm working with a dataset now which contains personal data. Without going into irrelevant details, the dataset spans a number of years, and some people (but not all) will reappear several times in the set, relating to different years. 

It is appropriate to obfuscate the personal information in some way, but in my case I also need to think about whether I need to be able to identify that the same person has appeared more than once in the data. This isn't necessarily obvious, it may be that for the particular features of the data that I am interested in each datum in the set is statistically independent, so one person appearing twice could be treated as two different people.

This makes quite a big difference in terms of how careful I need to be about being able to track participants in the dataset, and therefore _how_ I go about anonymising personal data.
