### ISSUE TITLE
Semantic versioning for datasets

### ISSUE THREAD

**Issue by snim2** [emhart/10-simple-rules-data-storage#27]
This is related to Issues #9, #10 and #11.

Datasets may well evolve over time. When reading a paper which describes an experiment on a particular dataset it should be possible to find out which _version_ of the dataset was used to produce the documented results. This aids reproducibility.

[Semantic versioning](http://semver.org/) is a common technique in software development. The idea is to provide a version number for the data which looks like: `MAJOR.MINOR.PATCH`
- the `MAJOR` version of the data, which should represent significant changes. In the case of datasets, this might mean that an experiment using version `1.0.0` of the dataset could not be run on version `2.0.0` without making some changes to the experiment, or the analysis of the results
- the `MINOR` version of the data which is compatible with other versions of the data which have the same `MAJOR` version. In the case of datasets, this might mean that any experiment or analysis performed on version `1.0.0` of the data should be repeatable with version `1.1.0` of the data.
- the `PATCH` version for bug fixes. For example version `1.0.1` of a dataset may fix a typo in version `1.0.1`.

**Comment by PBarmby** [comment]
Interesting idea. This might seem like a bit too much trouble to many people; I wonder if we can come up with an "at a minimum" recommendation, as in the [10 Simple Rules for Reproducible Computation](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003285) article. Actually, that would be a good thing for many of our proposed rules!

**Comment by snim2** [comment]
Good idea. 

A poorer way to do this is simply to document the date that the dataset was published and ask people to refer to that. Of course, this assumes you have relatively slow release cycles (i.e. you would not publish and update a dataset in the same day). Also, dates are written differently in different parts of the world. So, date of publication is a start, but it creates its own problems.

**Comment by wcornwell** [comment]
I like this idea, especially since the every analysis I've worked on has turned up minor errors in the data, so it would be good to get the software culture of patches to work in the world of data.  

One issue that this immediately raises (and maybe this is broader than this issue) is authorship and citation as new versions (potentially with different contributors) emerge.  How does this work in software development?

**Comment by snim2** [comment]
In a software project you would often have additional metadata to store that information. This might come in the form of a [ChangeLog](http://keepachangelog.com/) file (which details changes to each released version of the software, and _may_ include author information) and sometimes an [AUTHOR or CREDITS](https://github.com/torvalds/linux/blob/master/CREDITS) file. More often though, people will add their name to each file of source code they edit in a comment.
