### ISSUE TITLE
final call for rules

### ISSUE THREAD

**Issue by emhart** [emhart/10-simple-rules-data-storage#29]
Hi everyone.

By now our hope was that all rules will have been discussed.  Can we take the next couple of days to wrap up any further discussion and I will then synthesize what we've found and we can move on to voting for the rules.

**Comment by gvwilson** [comment]
http://www.w3.org/TR/2015/WD-dwbp-20150224/#bp-summary has 27 rules - 
are our 10 a subset?

**Comment by emhart** [comment]
I think some are, it's hard to imagine that you won't have some overlap.
