### ISSUE TITLE
References

### ISSUE THREAD

**Issue by emhart** [emhart/10-simple-rules-data-storage#3]
Here are some references for us.
## Original context of the e-mail.

Hi,

In case you missed it, Daisie Huang wrote a very insightful article
about the differences between scientific coding and software engineering
for the Software Sustainability Institute's blog at
http://www.software.ac.uk/blog/2015-02-06-scientific-coding-and-software-engineering-whats-difference.
I think short pieces like this that we can link to when we're talking to
colleagues (and writing proposals) are really useful, so I would be
grateful if a few of our newer instructors would like to volunteer to
summarize three recent discussions we've been having about:
- where scientists should store their data:
  https://github.com/swcarpentry/site/issues/797
## Guide to submitting a 10 simple rules

http://journals.plos.org/ploscollections/article?id=10.1371/journal.pcbi.1003858

**Comment by karawoo** [comment]
Related but distinct: [Ten Simple Rules for the Care and Feeding of Scientific Data](http://journals.plos.org/ploscollections/article?id=10.1371/journal.pcbi.1003542)

**Comment by PBarmby** [comment]
Also in the astronomy theme, [Reimplementing the Hierarchical Data System using HDF5](http://arxiv.org/abs/1502.04029v1) has some interesting comments on using different formats for processing, strage, and transport. I can translate jargon if necessary..

**Comment by arokem** [comment]
Hi everyone! This paper from our group may be of interest here: http://arxiv.org/abs/1502.06900

**Comment by jhollist** [comment]
New from PLOS one that might have some relevance (I have only looked at abstract):
http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0118053

**Comment by fmichonneau** [comment]
Blog post from NatureJobs on how to publish a data paper: http://blogs.nature.com/naturejobs/2014/12/04/how-to-publish-your-data-in-a-data-journal

**Comment by PBarmby** [comment]
Nice webpage from USGS that covers some of the same topics [http://www.usgs.gov/datamanagement/plan/dataformats.php](http://www.usgs.gov/datamanagement/plan/dataformats.php)

**Comment by emhart** [comment]
Closing because paper is now in production.
