### ISSUE TITLE
Finalizing rules

### ISSUE THREAD

**Issue by emhart** [emhart/10-simple-rules-data-storage#30]
Here's a summary of our discussion so far.  I think this
In no particular order.
1. Store data in an open format (ASCII, HDF5)
2.  Store data in multiple locations (Especially if using a local system)
3. Store data with a linkage to relevant metadata and license files
4. Consider the use case.  Permanent archive?  Regular usage? API? Personal archive? Storing to share?
5. Use semantic versioning of data, or at least some versioning system.
6. Keep raw data raw.  Data should be stored in as raw a format as possible
7.  Privacy concerns need to be considered.  How is data anonymized?  Is it linkable to anonymous personID?  Is it completely anonymized? What are the ethical and institutional concerns?
8. Data sets need to be uniquely identifiable 
9. Data storage solutions should be tailored to data size considerations.  Is this a few CSV's or terabytes of image data?  This links back to the use case.  Is it personal archiving? Sharing?
10. ??

This is my best effort at summarizing all the issues that people have filed.  I think we should take the next week or so to discuss this list, make any changes we want and then begin hashing out the writing distribution.  If each of us takes on a rule or two the writing should go pretty quickly.

**Comment by tpoisot** [comment]
I think a logical way to organize the rule would be for them to follow the usual data analysis workflow. With this approach, rule 1 would be something like "Know what to expect", which would cover both the type and size of the dataset. Then rules 2-10 would be about dealing with the aftermath.

**Comment by jhollist** [comment]
:+1:

**Comment by karawoo** [comment]
I like that idea, @tpoisot. Having any kind of conscious plan at all is a big and important first step.

**Comment by dlebauer** [comment]
Good list and suggestions so far. I think it would be good to discuss the
list here, but keep discussions of individual rules in their own
issues/threads, and authors can self-assign issues (?). Do any need to be
combined or dropped?

**Comment by naupaka** [comment]
One thing that isn't captured here in the list so far (I think) is having data be machine readable (i.e. easily parseable) if possible. ASCII is great but it should also be parseable ASCII (csv, tsv, etc) if possible. Something along the lines of Hadley's tidy data idea.

**Comment by gvwilson** [comment]
+1

**Comment by dlebauer** [comment]
Good point Naupaka, could be wrapped in with #11, #12,which is roughly
linked to 1 in this list, and also related to Kara's point about having a
plan.

**Comment by tpoisot** [comment]
Yes. We can talk about automated data validation too (like json schemes).

Envoyé depuis mon appareil Samsung

-------- Message d'origine --------
De : Greg Wilson notifications@github.com 
Date : 03/29/2015  7:51 PM  (GMT-05:00) 
À : emhart/10-simple-rules-data-storage 10-simple-rules-data-storage@noreply.github.com 
Cc : Timothée Poisot tim@poisotlab.io 
Objet : Re: [10-simple-rules-data-storage] Finalizing rules (#30) 

+1

**Comment by emhart** [comment]
@naupaka I think this issue touches a bit on the fact that this idea has always walked a fine line between best practices for storing vs best practices for publishing. I think we just need to be careful about highlighting how machine readable formats are important for storage, but otherwise :100:

**Comment by emhart** [comment]
@dlebauer I agree, we should really hash out specifics within the issues themselves.  I'm going to consolidate all the issues and give them #'s where assignment and further discussion can happen.

**Comment by emhart** [comment]
Ok, I've opened up issues with numbers now based on all the discussion and this thread.  I think we should aim to take about a week to hammer out and people should assign themselves to what they'd like to write.  Also after trying to consolidate our discussion I only came up with 8 issues.  So we have room for two more.  I'll work on coming up with a couple more but please add new ones if you have them in mind.
