### ISSUE TITLE
#1 Know What to Expect

### ISSUE THREAD

**Issue by emhart** [emhart/10-simple-rules-data-storage#31]
A suggestion from @tpoisot in #30. My interpretation is that starting out you need to take stock of your data and that this assessment will guide much of what follows in the rules.  You'll need to think about your use case, the type of data you have, the size of the data, how you're going to serve it up.

**Comment by snim2** [comment]
This looks nice! I'm not sure what you mean by "(i) create converters from these data". Do you mean that other people might want to have your dataset in a different format after you publish it, or that within your own workflow you will likely need to manipulate the data? Are the two things different?
