### ISSUE TITLE
#2 Know your use case!

### ISSUE THREAD

**Issue by emhart** [emhart/10-simple-rules-data-storage#32]
Researchers should know their use case and store data appropriately.  Is this data collected and just being archived? Will it change regularly? How will those changes be logged (e.g. provenance if any)?   Will this be shared via an API?  Linked to a paper?  What are the institutional restrictions?  Can you use a commercial service like Dropbox or use a personally maintained system?  Knowing the reason why you're sharing your data will constrain your choices here.  

refs: #16 and #19

**Comment by PBarmby** [comment]
Would everyone who reads this know what "use case" means? I wonder if that terminology might be difficult for non-native speakers. But I don't have an alternative yet..

**Comment by snim2** [comment]
@PBarmby since _use case_ is a term from software engineering, perhaps it is inappropriate. Maybe something like _understand how researchers will use your data_ would be suitable?

**Comment by karawoo** [comment]
I agree, "use case" is unnecessary jargon. @snim2 I like your suggestion.

**Comment by tpoisot** [comment]
Good point, I'll change that. Here are a few propositions:
1. Know how the data will be used
2. Understand how people will interact with your data
3. Know your data analysis pipeline

Any other suggestions?

**Comment by snim2** [comment]
Where you say "How do you track changes made to the data..." you might reference Rule 5 which has a discussion of how to version the release of a dataset.

**Comment by jhollist** [comment]
I like keeping it simple.  I think @tpoisot first suggestion or @snim2 suggestion would work, although some might argue we can't really know how it would/could be used.  "Use case"  does capture what we mean, but I agree that is feels jargony.   Perhaps something like:
- Understand how others might use your data
