### ISSUE TITLE
#3 Keep raw data raw

### ISSUE THREAD

**Issue by emhart** [emhart/10-simple-rules-data-storage#33]
Data should always be kept in a raw format whenever possible.  There's clearly some discussion about what constitutes "raw" (ohms off a temperature sensor?).  However the focus here is really on the spirit of the rule.  Data should be as "pure" as possible when it's stored.  If derivations occur, they should include storage of relevant code and subsequent data sets.

Refs: #20 and #12

**Comment by emhart** [comment]
Any interest in taking this one one @naupaka ?  It stems mostly from your suggestion.

**Comment by naupaka** [comment]
@emhart Sure thing. Is there yet a goal for wordcount/format for each of the topics?

**Comment by emhart** [comment]
The word count goal is between 150 - and 300 words, give or take.  Ideally it's going to be broken up into 1 or 2 paragraphs.

**Comment by PBarmby** [comment]
A quick search on "data product levels" suggests that it's a somewhat generic space/satellite thing (I'm familiar with it from astronomy) as well as partinent to NEON. Would be good to mention the general idea (level 0 = raw, higher levels = more processing, etc).

**Comment by emhart** [comment]
It also refers to some NASA EOS data, NOAA data (http://www.ngdc.noaa.gov/wiki/index.php?title=NOAA_Processing_Levels) etc.  NEON adopted these levels to be congruous with other data products.

**Comment by snim2** [comment]
I like the discussion of raw vs. derived data here. Where you say "We defined raw data as things like voltage" it isn't clear who "we" refers to. Also, it would be really interesting to have a bit more detail about the ATBDs, if it can fit into the word count!
