### ISSUE TITLE
#4 Data should be stored in open formats

### ISSUE THREAD

**Issue by emhart** [emhart/10-simple-rules-data-storage#34]
All data should be stored in common binary or open formats. Examples are ASCII, NetCDF or HDF5. Furthermore, these formats need to parseable for the foreseeable future.  ASCII should be in a format such as csv, or a documented delimiter, binary formats should probably have some assurances of future support.

Refs #12 and #30

**Comment by emhart** [comment]
@PBarmby Do you think here is an appropriate place to address database technologies?

**Comment by dlebauer** [comment]
> All data should be stored in common **binary or open** formats.

Is 'binary vs open' an appropriate dichotomy? Aren't HDF5, NetCDF, and .Rdata all both open and binary?

>  appropriate place to address database technologies

To clarify - is there a principled definition of 'database' here that will distinguish it from alternative methods of data storage? For example, ANSI SQL - compliant RDBMS would probably cover most of what people know to be databases. On the other hand, a 'database' is a generic term for a place to store data - which easily encompasses HDF5, NetCDF, csv, tables in memory, spreadsheet worksheets, email accounts, and filesystems (to name a few)?  

Or, what is the difference between SQLite and HDF5?

**Comment by PBarmby** [comment]
My understanding is that people usually use "binary" to distinguish from "human-readable", yes?
What we're after is the idea tostore data in a format that does not requre proprietary software to access, I think -- so either binary (eg HDF5) or human-readable (csv) would be "open", as would
some but not all forms of database file storage formats.

I was going to say to @emhart that "not everybody stores their data in a database" but depending on how broad your definition is (eg @dlebauer's list of "places to store data") maybe everybody does. Hmm, think I need to think about this more..

**Comment by snim2** [comment]
@PBarmby +1
