### ISSUE TITLE
#8 What is your back-up scheme?

### ISSUE THREAD

**Issue by emhart** [emhart/10-simple-rules-data-storage#38]
Data should have back-ups!  These will differ greatly by use case.  If your data is small it could just be back-up hard drives.  If it's large data stored in an institutional repository, what is the back-up system? If it's stored on a commercial service, what do they use?

Ref #10

**Comment by PBarmby** [comment]
I suggest a reference to Rule 7 here (or a reference to rule 8 in rule 7) -- in some cases knowing the physical location of the cloud server is important if privacy rules differ between jurisdictions.

**Comment by snim2** [comment]
Is there a nice reference for the Toy Story anecdote? I've seen this Quora answer:

http://www.quora.com/Did-Pixar-accidentally-delete-Toy-Story-2-during-production/

but it would be nice to have something with a DOI.
