### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by emhart** [emhart/10-simple-rules-data-storage#40]
Write an intro for the submission.  Goal is 1 to 2 paragraphs, approximately 500 words.

**Comment by snim2** [comment]
A nice introduction has been added to the manuscript, I think we can close this issue?

**Comment by jhollist** [comment]
:+1:

On Thu, Jul 23, 2015 at 8:15 AM, Sarah Mount notifications@github.com
wrote:

> A nice introduction has been added to the manuscript, I think we can close
> this issue?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/emhart/10-simple-rules-data-storage/issues/40#issuecomment-124078420
> .

## 

Jeff W. Hollister
email: jeff.w.hollister@gmail.com
google voice: 401 326 2531
cell: 401 556 4087
