### ISSUE TITLE
#10 Data should be stored in machine readable formats?

### ISSUE THREAD

**Issue by emhart** [emhart/10-simple-rules-data-storage#41]
@naupaka brought this up in #30 and it's also mentioned in http://www.w3.org/TR/2015/WD-dwbp-20150224/#MachineReadableStandardizedFormat  

It facilitates reproducibility and enables easier provenance.  It also makes creating API's easier and moving between database system easier.

**Comment by PBarmby** [comment]
This is important, for sure. Let's see how we integrate it with #34 (rule 4) so they similar but not identical.

**Comment by emhart** [comment]
I had the same thought, as @naupaka pointed out open != machine readable, but they are quite closely related.  Thanks for taking this one on @fmichonneau

**Comment by jhollist** [comment]
Was just reading through @PBarmby PR on rule 4 and was going to suggest adding in some text on machine readable aspect, but then saw this.  I wonder if having Rule 4 and Rule 10 sequential would make sense?

**Comment by fmichonneau** [comment]
It would make sense to me to have this rule follow rule 4.

I think it would also make sense for this rule to be followed by rule 6 as there will be overlap in the machine readable aspect of the data and the metadata. I'm happy to defer this decision until the rules start taking shape.

I'm planning to have an outline for this rule ready by Sunday evening.

**Comment by fmichonneau** [comment]
a draft for this rule is in the manuscript.
