### ISSUE TITLE
Writing workflow / timeline

### ISSUE THREAD

**Issue by emhart** [emhart/10-simple-rules-data-storage#42]
We now have a draft list of 10 issues.  Let's set a goal of writing them up in 2 weeks, e.g. drafts up in the repository by April 23rd.  Any issues that people don't assign themselves to I'll try and write.  There are still a couple unassigned issues.  So if there's an issue you'd like to take on, please assign yourself.  If the issue is already taken, please volunteer to help in the comments.  Most 10 simple rules paper rules tend to bet about 150-300 words and 1 to 2 paragraphs.  Obviously feel free to write more or less than that, it's just a guideline.  

Thanks for all your work everyone.

**Rough Timeline**
- April 23rd paragraphs written
- April 30th Draft assembled
- May 7th comments on assembled draft

**Comment by snim2** [comment]
I notice that your makfile autogenerates LaTeX and PDF from the Markdown source. This is really neat! Is there any particular reason for having the generated files (.tex, .aux, .out, .dvi, .pdf, .lg, .out) committed to the repository? This confused me at first, and it has the potential for the generated files to get out of sync with the MD text.

Also, I think it would be neat to have a `make clean` target to remove the generated files. Are you OK with me issuing a PR for that?

**Comment by jhollist** [comment]
@emhart Since I don't have complete ownership on any of the rules, I can take a first pass once all the draft rules have been merged.  And if I am feeling it, I can attempt an intro.

**Comment by PBarmby** [comment]
What's the best way to comment on the assembled draft? New issues? comments on existing issues?
[Print it out, write on the paper, scan the paper, email it to everyone?]

**Comment by emhart** [comment]
The latter of course :laughing: Seriously though.  My first thought is that we should comment in the issue for the particular rule if you have have general comments.  However if you want to make edits to a rule, I'd make the edits, possibly add comments in the MD as HTML comments, and then submit a PR and ping the main author.  That way the author can discuss the changes to the manuscript with the editor.  But if people have other approaches they prefer please bring them up.

**Comment by PBarmby** [comment]
I'm about to go offline for a couple of weeks; I think I've made what useful comments I can, so please don't wait for me for the next step. Thanks all!

**Comment by emhart** [comment]
Thanks Pauline.  We're waiting for one last rule from Tim and then we'll
assemble the entire manuscript into a more coherent paper.

**Comment by tpoisot** [comment]
Just out of curiosity, which rules is this? I think I submitted PR for 1 & 2, was I supposed to do a third one?

**Comment by emhart** [comment]
It's rule 7 on privacy, which Tim Church is writing.  I've spoken with him
and he said he should have something within the next week.

**Comment by tpoisot** [comment]
Right, so the _other_ Tim. Gotcha.
