### ISSUE TITLE
Zenodo?

### ISSUE THREAD

**Issue by tpoisot** [emhart/10-simple-rules-data-storage#52]
Should we mention Zenodo somewhere? They offer DOI for datasets, and (being CERN-operated) have both super-duper large storage and are a grassrot initiative.

**Comment by snim2** [comment]
I mentioned it in Rule 5 if that is any help. You can see the text in PR #50

**Comment by emhart** [comment]
I think it's worth it as an example of where to store your data

**Comment by emhart** [comment]
I think we have this covered, so I'm closing.
