### ISSUE TITLE
Editing manuscript.

### ISSUE THREAD

**Issue by emhart** [emhart/10-simple-rules-data-storage#60]
Hi Everyone.

We now more or less have a rough draft on the entire manuscript.  I'd like to begin the editing process.  Some of the rules are in various stages of completion, but at this point I think it'd be most productive if everyone feels open to edit any part of the manuscript.  If you haven't written an issue and you'd like to contribute still this is your chance.  My only thought is that we should submit all edits as PR's so everyone can have a chance to comment on edits.  My hope is that we can spend a few weeks editing and then submit a pre-print for further comment before submitting to PLoS (if people are ok with this plan).  Does this sound good?

**Comment by snim2** [comment]
+1

**Comment by jhollist** [comment]
Sounds good!

**Comment by naupaka** [comment]
+1

**Comment by fmichonneau** [comment]
+1

**Comment by dlebauer** [comment]
Yep

**Comment by tpoisot** [comment]
Sounds great.

**Comment by karawoo** [comment]
Sounds good to me.

**Comment by jstearns** [comment]
I'd like to read it over if that's ok.
