### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by gvwilson** [emhart/10-simple-rules-data-storage#65]
```
$ pandoc --version
pandoc 1.13.1
$ pwd
~/10-simple-rules-data-storage/manuscript
$ make
pandoc --filter pandoc-citeproc -S --standalone manuscript.md --template=resources/plos_template.tex -o manuscript.tex
pandoc-citeproc: "stdin" (line 395, column 2):
unexpected "a"
expecting "c", "C", "p", "P", "s" or "S"
pandoc: Error running filter pandoc-citeproc
make: *** [manuscript.tex] Error 83
```

Am I running the wrong version of pandoc?

**Comment by snim2** [comment]
I get something similar. I think the problem stems from this issue:

https://github.com/jgm/pandoc-citeproc/issues/81

**Comment by snim2** [comment]
Depressing workaround on Ubuntu (tl;dr packaged citeproc is b0rked, install from github):

``` bash
$ sudo apt-get remove pandoc-citeproc pandoc
$ sudo apt-get autoremove
$ sudo apt-get install ghc cabal-install cpphs
$ cabal update
$ cabal install hsb2hs # Missing dependency in the Makefile
$ git clone git@github.com:jgm/pandoc-citeproc.git
$ cd pandoc-citeproc
$ cabal configure
$ make quick
$ make install # Might need sudo
```

**Comment by naupaka** [comment]
Works fine for me, using `pandoc 1.13.2.1` and `pandoc-citeproc 0.7.0.1`. There have been a decent amount of changes to `pandoc` recently that haven't made it into all the package managers, so I have installed from GitHub ([here](https://github.com/jgm/pandoc/releases/tag/1.15.0.6)) instead of via homebrew on OS X. Not sure if that's why?

You may also have to separately install `pandoc-siteproc`? That's what tripped me up the first time I tried to build.

**Comment by snim2** [comment]
Breaks for me with `pandoc 1.15.0.6` and `pandoc-citeproc 0.4.0.1` which are default on Ubuntu 15.04. The instructions above currently install `pandoc-citeproc 0.7.2`

**Comment by emhart** [comment]
I get an error with parsing lists on my machine with pandoc 1.15.0.6

```
[1]
! Undefined control sequence.
l.259 \tightlist
```

It works fine on my laptop though, which is running pandoc 13.2.1

**Comment by karawoo** [comment]
@emhart I also get that error with pandoc 1.15.0.6.

**Comment by naupaka** [comment]
Hmmm. I just pulled from master and now mine is broken as well. 
Versions: `pandoc 1.13.2.1` and `pandoc-citeproc 0.7.0.1`

**Comment by gvwilson** [comment]
This is why we can't have nice things.

**Comment by emhart** [comment]
So true...
![](http://38.media.tumblr.com/8774161d32300700ee4259696a49c330/tumblr_n7ruu5vZid1smcbm7o1_400.gif)

**Comment by jhollist** [comment]
Maybe this is a sign of me using too much Twitter, but I really want to favorite these last two comments...

**Comment by naupaka** [comment]
Hooray! Also fixed it for me. Thanks @karawoo

**Comment by fmichonneau** [comment]
It works for me as well, so closing for now. Thanks @karawoo !
