### ISSUE TITLE
Create glossary

### ISSUE THREAD

**Issue by fmichonneau** [emhart/10-simple-rules-data-storage#71]
After reading through the manuscript, it seems that there are a ton of acronyms/abbreviations that may not be familiar to the target audience. We could try to reduce them when possible, but I otherwise suggest we create a glossary to help readers navigate.

**Comment by fmichonneau** [comment]
Any thoughts on this? I'm willing to write a first draft.

**Comment by jhollist** [comment]
I think it is a good idea.   Could be one of the most used pieces of this
paper!

On Mon, Sep 21, 2015 at 2:28 PM, Francois Michonneau <
notifications@github.com> wrote:

> Any thoughts on this? I'm willing to write a first draft.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/emhart/10-simple-rules-data-storage/issues/71#issuecomment-142068328
> .

## 

Jeff W. Hollister
email: jeff.w.hollister@gmail.com
google voice: 401 326 2531
cell: 401 556 4087

**Comment by emhart** [comment]
:+1: on this, do you have anything to share yet, or maybe do you want  to throw up some terms in the issue?

**Comment by fmichonneau** [comment]
I'll work on it this weekend.

**Comment by emhart** [comment]
Closing because the glossary was merged last week, and it's really fucking awesome.
