### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by tpoisot** [emhart/10-simple-rules-data-storage#74]
Hi all,

Do we have a timeline to submit this paper?

If it helps move things forward, I can do a round of editing.

t

**Comment by emhart** [comment]
Well, we did but summer seems to have gotten away from me :disappointed: , but I agree we've all put in a good deal of work, and we should see it through to submission.  I think everyone has done a great job with their rules.  If you've got the cycles @tpoisot why don't you take a pass, I'll take one more and then we'll post as a pre-print. 

Let's set a goals.  
- Preprint by Monday Sept. 21st
- Submitted by Oct. 16th.

I think we're in the home stretch now. 

One final thought, do these papers have page charges?  If so do we have anyone that can pick them up?

**Comment by naupaka** [comment]
I think this sounds like s good timeline.

PloS Comp Bio is not cheap:

> PLOS Computational Biology publication fees are US$2250 per manuscript and will be billed upon acceptance. Authors’ ability to pay publication fees will never be a consideration in the decision whether to publish.

But perhaps either someone has funds or else they would be willing to waive the fee?

**Comment by fmichonneau** [comment]
:+1: on the timeline

For the APC, could it be something that the software carpentry foundation cover in part?

**Comment by tpoisot** [comment]
:+1:  on the timeline. :shipit: !

I'll have a look tomorrow. That would be a welcome distraction in between grant editing and comittee meeting. :tada: 

For the charges, we can ask for a waiver. Especially since there seem to be an additional charge for [collections](https://www.plos.org/publications/publication-fees/special-collection-fees/). If they disagree or don't waive it all, those of us with research money can maybe split the bill?

**Comment by jhollist** [comment]
Wow, 3k is a lot...   

So, I just ran this request up the line here and we may have some funds that could support this, but not at 3k.  If we could ask for a waiver first that would be good. Full waiver would be best, but If we get a partial waiver  then, assuming I can navigate our purchasing, I might be able to cover.  Still need to check on a few things and get a final :+1: , but odds look somewhat good.

**Comment by emhart** [comment]
Anyone have any last comments/edits to make before we post as a preprint?

**Comment by naupaka** [comment]
I don't think @tpoisot (or anyone else) fixed comments by @jhollist. Those (on PR #75 ) still need to be fixed, AFAICT.

**Comment by dlebauer** [comment]
I'd like to take another look. What is the target submission date?

**Comment by jhollist** [comment]
I'll read through this morning and make changes I suggested on #75 plus
anything else I find.

**Comment by emhart** [comment]
Great, thanks everyone... @dlebauer I think we're hoping to make the submission in a month or so.  I think at this point we just need a bit of concerted effort to cross the finish line.

**Comment by emhart** [comment]
I took a last pass after merging the glossary changes.  I'm satisfied enough to push it up to a preprint server in the next couple days.
