### ISSUE TITLE
Drop last paragraph of Rule 3

### ISSUE THREAD

**Issue by fmichonneau** [emhart/10-simple-rules-data-storage#79]
I don't find the last paragraph of Rule 3 (example of how NEON handles raw data) really clear, and I'm not sure it adds value to this rule. Should we drop it? If not, I think it would need to be rewritten to be made clearer.

**Comment by naupaka** [comment]
I agree. I think the rule reads better without the last paragraph. The point is well made even before the NEON, etc examples.

**Comment by jhollist** [comment]
:+1:
