### ISSUE TITLE
Acknowledgements

### ISSUE THREAD

**Issue by emhart** [emhart/10-simple-rules-data-storage#87]
Before I submit to a pre-print server, can folks make sure they have what they need in there?  e.g. @jhollist the EPA stuff we'll need etc...

**Comment by jhollist** [comment]
As long as I'm not 1st, 2nd, or 3rd, I don't need to send paper through
review.  I also don't think I need to add anything to the acknowledgements,
but I'll check today.

**Comment by emhart** [comment]
@snim2 @dlebauer @PBarmby  @karawoo Do you have any funding agency text you need to add to the acknowledgements?  Please paste it here and I can add it or send a PR, whichever is easier.  Thanks!

**Comment by dlebauer** [comment]
I was funded by the Energy Biosciences institute and the National Center
for Supercomputing Applications

**Comment by PBarmby** [comment]
I was funded by the Natural Sciences & Engineering Research Council of Canada and the Academic Development Fund of the University of Western Ontario.

**Comment by snim2** [comment]
No funding agency ACKs for me.

**Comment by karawoo** [comment]
I should acknowledge Washington State University.
