### ISSUE TITLE
One preprint server to rule them all

### ISSUE THREAD

**Issue by emhart** [emhart/10-simple-rules-data-storage#88]
Does anyone have any strong feelings on this?  PeerJ or arXiv?

**Comment by naupaka** [comment]
Either would be fine with me.

**Comment by jhollist** [comment]
No strong opinions here either.  I've used peerj before and thought it was
nice...

**Comment by PBarmby** [comment]
No experience with PeerJ (plenty with arxiv). So no preference but can help with the logistics of arxiv if needed.

**Comment by snim2** [comment]
I guess the question is: which server does the intended audience prefer? Personally I have no particular preference...

**Comment by karawoo** [comment]
Either one is fine with me as well.

**Comment by naupaka** [comment]
I'll add my +1 for PeerJ (although definitely not anti-arXiv by any means). Have had several very positive experiences with using PeerJ's preprint server.

**Comment by emhart** [comment]
Ok, submitted to PeerJ Computer Science Preprints.

**Comment by jhollist** [comment]
:+1:

**Comment by fmichonneau** [comment]
Thanks Ted!

**Comment by karawoo** [comment]
:fireworks:

**Comment by tpoisot** [comment]
:arrow_right: :computer: :bar_chart: :memo: :clap: :clap: :clap:  !
