### ISSUE TITLE
A shout out to everyone.

### ISSUE THREAD

**Issue by emhart** [emhart/10-simple-rules-data-storage#89]
Can I just say that I think SWC community/ Twitter / the internet is rad?  In reading through this paper two thoughts struck me.  
1. This paper is pretty good right?  I enjoyed reading it and thought it was full of really useful advice.
2. Most of the authors have never met each other in real life.  Essentially nine strangers from myriad disciplines came together and wrote the aforementioned awesome paper.  That's pretty amazing when you think about it.  We used all the open tools that we teach to accomplish a completely distributed collaborative project.  Maybe others aren't impressed, but I'm really impressed by everyone's efforts.  So thank you everyone for all your work.  :clap:

**Comment by jhollist** [comment]
+100!

**Comment by fmichonneau** [comment]
I agree, :clap: :clap: :clap: everyone!

Thanks @emhart for organizing this!

**Comment by jhollist** [comment]
Yes, thanks @emhart.  Next scotch is on me.

**Comment by tpoisot** [comment]
:clap: -- it's been a great experience, and I too think it's a pretty good resource.

**Comment by snim2** [comment]
+1
