### ISSUE TITLE
Thoughts of Figure 1, which I really like

### ISSUE THREAD

**Issue by dlebauer** [emhart/10-simple-rules-data-storage#90]
I am about to take a hack at this over the weekend. I will put in at least one more pull request right now.

Also, for figure 1 - kudos @fmichonneau . A great addition. 

<img width="634" alt="screen shot 2015-10-16 at 9 32 18 pm" src="https://cloud.githubusercontent.com/assets/464871/10556616/e9cdcbb0-744d-11e5-83cd-fdc4d5d91cf1.png">

I have a few ideas that might make some key points more explicit.
- Label tables one and two as metadata, and label columns 1-3 on table 1 as what/where/when (also meta-data). These are a few ideas that are very simple, but critical, and could easily be illustrated here, perhaps some of the following could be added to the legend: 
  1. metadata is a fancy term for context. For each data point you need to know what, when where. 
  2. (corollary to i)The top table is used in analysis  
  3. This is a relational database (another fancy term but accessible concept), but in many (most?) cases it won't be necessary to join these tables for a statistical analysis. Metadata may only show up in a README, methods section, table, or appendix but not necessarily used to fit a statistical model (though sure, plenty of covariates fit in such 'lookup tables').
- it would be sufficient if the first table had columns `species_code`, `genus`, `species` - this would reinforce the logic used to split `latitude longitude` into separate fields. Perhaps have another row with one genus duplicated but different species. As it is, it is difficult to see the advantage over replacing `species_code` with `species_name` in the third table.
- Put the table with important data first.
- the lines, boxes, and labels are intended to illustrate the concepts above and information to include. Perhaps also the lines linking primary and foreign keys that would help familarize readers with standard relational database modeling. Just a thought. But maybe I am over-complicating this. I am happy to work on this unless you want to take it on.

<img width="769" alt="screen shot 2015-10-16 at 10 21 04 pm" src="https://cloud.githubusercontent.com/assets/464871/10556860/d849dffa-7457-11e5-9902-56e149f05800.png">

**Comment by emhart** [comment]
Interesting ideas @dlebauer 

I definitely think it's good to label the tables as data a metadata, and in fact labeling tables is explicitly mentioned in Rule 6.  

I think points i. and ii. are good, it makes metadata seem more approachable to people.  It says "You know what this is, here's a fancy name for something you do all the time"  

I also like the logic of separating out `species_name` into `species` and `genus`.  

My only concern is the lines linking the keys.  I think that might be over complicating it and could make the figure to busy.  I think familiarizing readers with concepts about RDBMS is beyond the scope of this paper.  But feel free to take crack at it and we can check it out and discuss.

**Comment by emhart** [comment]
@dlebauer The only thing is that I'd like to put up a pre-print by Sunday evening if you think you can have a draft up by then.

**Comment by dlebauer** [comment]
Ok I can take a whack. Suggestions for editing .eps?

**Comment by tpoisot** [comment]
I'm going to be a killjoy here, but species names are meh. Can we add things like NCBI taxid, TSN, or the like in the table?

`Alligator mississippiensis TSN 551771`, `Puma concolor TSN 55247`, and `Ursus americanus TSN 180544`

**Comment by tpoisot** [comment]
(That would go in the blue table, by the way)

**Comment by dlebauer** [comment]
Ted: I agree about dropping the primary / foreign key links. At the scale
of a few tables and a few fields, this is easy enough to comprehend.

Timothée - I agree that species / genus is meh and also that a unique
taxonomic identifier would be more useful, since it could be used to
reference a more canonical source for taxonomic classification. So having a
field with a unique identifier that has a canonical source and is a common
point of reference for many datasets is an important point to illustrate.

What about another field that provides information that could be used in a
study, and that is not unique, e.g. a 'furry' Boolean field to illustrate
classification?

If you have time and interest in revising the figure, that would be great.

For the groupings, an alternative to the boxes I drew would be to use color
or font to distinguish 'meta-data' from 'data'. This could decrease the
clutter if the labels 'meta-data' and 'data' also used the identifying
fonts.

**Comment by fmichonneau** [comment]
Thanks for the feedback!

I agree with Thimothée about adding taxon identifiers such as TSN in the table, that would better than using the 2 letter species codes.

With my "museum data" background, the "what, when, where" seems more like data than metadata but I totally see your point, and I think that it can be a good opportunity to illustrate these concepts.

I also like the split of genus and species to justify the existence of the second table. 

I agree with Ted that introducing the RDBMS is a little out of scope. The main idea here was to illustrate how to reduce the duplication of information.

I'll push these changes to the repo and add the SVG file as well if you want to modify the figure further.

**Comment by fmichonneau** [comment]
David, I hadn't seen your latest comment before posting mine.

I pushed the modified version of the figure (and the SVG file, created with inkscape) to the repo. I haven't done anything about the meta-data/data distinction at this stage. I can give it a try tomorrow (as I'm busy for the rest of the day) but if someone else wants to give it a go, please do!

**Comment by dlebauer** [comment]
@fmichonneau I don't see the svg file ... Could you link to it?

**Comment by fmichonneau** [comment]
oops, sorry I was in a hurry yesterday and pushed to my fork instead of
upstream. It's fixed now, and the figure is in
manuscript/resources/tidy_data.svg

**Comment by dlebauer** [comment]
@emhart Can I have a few hours? 10 Pacific / 5 GMT?

**Comment by dlebauer** [comment]
@fmichonneau I've made some changes and pushed to a branch fig1-revisions. I used color to de-emphasize 'untidy' data and to emphasize the distinction between meta-data and data (though I agree with you that this is not black and white (or red and blue, below) 

These are in pull request #98

<img width="692" alt="screen shot 2015-10-18 at 11 24 27 pm" src="https://cloud.githubusercontent.com/assets/464871/10569670/6d184aac-75ef-11e5-9540-23d36e86fdf0.png">

**Comment by emhart** [comment]
I'd like a few more folks to chime in on this, but my opinion:
1. I found @fmichonneau boxes a bit easier to read with the colors.  Also the red/blue color scheme shouldn't be used to account for color blind readers
2. I like the titles in @dlebauer figure for **Tidy Data** and **Untidy Data**
3.  I feel conflicted about the "What/ When etc.." labels.  Yes I think they are clarifying as I mentioned earlier, but now seeing them in action, I find them visually cluttering, and confusing because the tables are stacked but those labels only apply to the first table.
   - I think removing the "?" would be helpful
   - The stacking is confusing.  I think adding a separate a line with a header saying "Metadata table" or a different color background?  Not sure what the best solution is here.

However, I worry that by breaking the tables out to this degree of granularity we risk going down the metadata rabbit hole. I'd love another few sets of eyes on this.   But I think we're close with the figure.

**Comment by naupaka** [comment]
My 2¢:
- The Tidy/Untidy labels are useful
- The what/when/where labels could be removed -- a agree that they are a bit cluttering
- I found the visual color boxes from @fmichonneau's version more visually appealing, but I also appreciate the added point @dlebauer is making by pointing out how much of the data is really metadata, and how important this is.
  - Maybe a hybrid of the two where the different tables have colored (or even light grey) backgrounds?

**Comment by fmichonneau** [comment]
I'll try to come up with an updated version that takes into consideration Ted and Naupaka's feedback a little later today.

**Comment by naupaka** [comment]
I'm working on a new version now... I'll stick it here in the comments and if it's worth using/tweaking I can do a PR.

**Comment by naupaka** [comment]
Here's my updated version (as a png to embed, although original is an svg). I also added units to the length and weight and tweaked some of the spacing.

![tables_2-01](https://cloud.githubusercontent.com/assets/1428071/10612881/a68643ca-7707-11e5-81c8-e7d1f112b07a.png)

**Comment by fmichonneau** [comment]
Thanks @naupaka! It looks great to me. Please merge in the manuscript. The only thing would be to center the word "data" with respect to the weight/length columns (so the middle of the word lines up with the column separator).

**Comment by naupaka** [comment]
"data" header centered and PR submitted.

**Comment by emhart** [comment]
Looks great!  Thanks for the work everyone!
