### ISSUE TITLE
Rename Rule #1?

### ISSUE THREAD

**Issue by snim2** [emhart/10-simple-rules-data-storage#97]
Rule 1 **Know what to expect** is a little vague. Clearer titles might be something like:
- Anticipate how your data will be used
- Anticipate rather than react

or similar?

**Comment by dlebauer** [comment]
I agree it is vague. How about "Prepare data so that it can be reused"?

**Comment by emhart** [comment]
Care to chime in @tpoisot ?  I believe you wrote it so I'll let you decide what you think it should be named.

**Comment by emhart** [comment]
This is the last issue before posting to PrePrint so I'm going to go ahead, if we agree on a change we can make it in the submitted version.

**Comment by naupaka** [comment]
I like "Anticipate rather than react".
